appname = "transbot"
version = "0.1.0"

[notion]
	api_auth = "<your notion api auth key>"
	base_url = "https://api.notion.com"
	version = "2022-06-28"

[openai]
	api_key = "<your openai api key>"
	temperature = 0.7
	model = "gpt-3.5-turbo"
	# model = "gpt-4"
[4everland]
	key = "<your bucket key from 4everland>"
	secret = "<your bucket secret from 4everland>"
	endpoint = "https://endpoint.4everland.co"
	bucket_name = "<your bucket name>"

[service]
	port = 8080
	tls = false
	tls_key = "./cert/key.pem"
	tls_cert = "./cert/cert.pem"